FROM ubuntu:14.04
COPY TARGET/* /src/
RUN apt-get install -y tar libfreetype6  && tar -C /src/ -xvf /src/CDOT-MCU.tar && cd /src/CDOT-MCU && ./cdotmcu_install.sh && rm -rf /src/*

CMD ["/opt/CDOT-MCU/bin/cdot-mcu" , "-x &" ]

