FROM ubuntu:14.04
COPY TARGET/* /src/
RUN apt-get install -y tar libfreetype6-dev  && tar -C /src/ -xvf /src/CDOT-MCU.tar && cd /src/CDOT-MCU && ./cdotmcu_install.sh && rm -rf /src/*

CMD ["echo","Hello vish kindly check the /opt/CDOT-MCU for proper installation"]
